version: '3.4'

networks:
  dev:
    name: dev
    driver: bridge

volumes:
  cash_flow_data:
  pgadmin:

services:

  cash-flow-db:
    image: postgres:latest
    container_name: cash-flow-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cashflow
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - cash_flow_data:/var/lib/postgresql/data/ 
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - dev    
    
  cash-flow-service:
    container_name: cash-flow-service
    image: ${REGISTRY:-cash-flow}/cashflow.api:${PLATFORM:-linux}-${TAG:-latest}
    depends_on:
      cash-flow-db:
        condition: service_healthy
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 200M
    links:
      - cash-flow-db
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: always
    environment:
      - ConnectionString= User ID=postgres;Password=postgres;Host=cash-flow-db;Port=5432;Database=cashflow;Pooling=true;
    ports:
      - 5000:80
      - 5001:443
    networks:
      - dev  
  
  influxdb:
    image: influxdb:1.8
    networks:
      - dev
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - dev
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: loadimpact/k6:latest
    networks:
      - dev
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts


  # pgadmin:
  #   container_name: pgadmin-db
  #   image: dpage/pgadmin4
  #   environment:
  #     pgadmin_default_email: ${pgadmin_default_email:-pgadmin4@pgadmin.org}
  #     pgadmin_default_password: ${pgadmin_default_password:-admin}
  #     pgadmin_config_server_mode: 'false'
  #   ports:
  #     - "${pgadmin_port:-5050}:80"
  #   volumes:
  #      - pgadmin:/var/lib/pgadmin
  #   networks:
  #     - dev
  #   restart: unless-stopped