version: '3.4'

networks:
  dev:
    name: dev
    driver: bridge 

volumes:
  cash_flow_data:
  pgadmin:

services:

  cash_flow_db:
    image: postgres:latest
    container_name: cash_flow_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cashflow
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - cash_flow_data:/var/lib/postgresql/data/ 
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - dev    
    
  cash-flow-service:
    container_name: cash-flow-service
    image: ${REGISTRY:-cash-flow}/cashflow.api:${PLATFORM:-linux}-${TAG:-latest}
    depends_on:
      cash_flow_db:
        condition: service_healthy
    links:
      - cash_flow_db
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: always
    environment:
      - ConnectionString= User ID=postgres;Password=postgres;Host=cash_flow_db;Port=5432;Database=cashflow;Pooling=true;
    ports:
      - 5000:80
      - 5001:443
    networks:
      - dev  
  
  pgadmin:
    container_name: pgadmin_db_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
       - pgadmin:/var/lib/pgadmin
    networks:
      - dev
    restart: unless-stopped